### ISSUE TITLE
Bug menu em serviços Mobile

### ISSUE THREAD

**Issue by ArthurViniNunes** [ApenasUmSonhador/Tatame-Universitario#1]
Em "Quem somos?" há um problema no clique do header para dispositivos mobile. O clique não está abaixando o header de maneira devida.

**Comment by Jose-Alberto-Rodrigues-Neto** [comment]
Isso ocorre pq em uma das atualizações vc acabou apagando sem querer o id:"mobNav", q é utilizado no corpo do javascript implementado no header. Tentei mudar, mas tive problemas com push no github do arquivo no meu pc, n sei exatamente ao certo o motivo do problema. Mas pra resolver é só colocar o id q eu falei na imagem do header responsivo. 

Se olhar o corpo do header no meu último push/commit, da pra ver o que eu to falando.
